# basic image
FROM centos:7.6.1810

MAINTAINER ylyxf "304189773@qq.com" 

WORKDIR /root

RUN curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && \ 
	yum install wget -y && \
#java
	yum install java-1.8.0-openjdk java-1.8.0-openjdk-devel -y && \
#ant
	mkdir /usr/ant && \
	wget  -O apache-ant-1.10.5-bin.tar.gz http://mirrors.tuna.tsinghua.edu.cn/apache//ant/binaries/apache-ant-1.10.5-bin.tar.gz  && \
	tar zxvf apache-ant-1.10.5-bin.tar.gz -C /usr/ant  && \
	rm -r apache-ant-1.10.5-bin.tar.gz && \
	rm -R -f /usr/ant/apache-ant-1.10.5/manual && \ 
#maven
	mkdir /usr/maven && \
	wget  -O apache-maven-3.6.0-bin.tar.gz http://mirrors.tuna.tsinghua.edu.cn/apache/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz  && \
	tar -vxzf apache-maven-3.6.0-bin.tar.gz  -C /usr/maven && \
	rm -f apache-maven-3.6.0-bin.tar.gz && \
#git
	yum install git -y && \	
#nodejs
	curl -sL https://rpm.nodesource.com/setup_11.x | bash -  && \	
	yum install nodejs -y && \	
#mkdocs
	yum -y install epel-release	 && \
	yum -y install python-pip && \
	pip install mkdocs && \
#clean
	yum clean all && \
	rm -rf /var/vache/yum
	 
ENV JAVA_HOME /usr/lib/jvm/jre-openjdk
ENV ANT_HOME /usr/ant/apache-ant-1.10.5
ENV MAVEN_HOME /usr/maven/apache-maven-3.6.0
ENV PATH "${PATH}:$ANT_HOME/bin:$MAVEN_HOME/bin"


 